services:
  yomiko.debug:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: yomiko.debug
    mem_limit: "${YOMIKO_MEM_LIMIT:-768m}"
    ports:
      - 62080:80
    environment:
      YOMIKO_CONVERSION_JOBS: "${YOMIKO_CONVERSION_JOBS:-1}"
      MAGICK_MEMORY_LIMIT: "${MAGICK_MEMORY_LIMIT:-256MiB}"
      MAGICK_MAP_LIMIT: "${MAGICK_MAP_LIMIT:-256MiB}"
      MAGICK_THREAD_LIMIT: "${MAGICK_THREAD_LIMIT:-1}"
    volumes:
      - "${HOST_HATH_DOWNLOAD_DIR}:/home/yomiko/hath"
      - "${HOST_ARCHIVED_DIR}:/home/yomiko/archived"
      - "../data:/home/yomiko/data"
      - "../logs:/home/yomiko/logs"
    develop:
      watch:
        - action: sync+restart
          path: ../bin
          target: /home/yomiko/bin
        - action: sync+restart
          path: ../cronjobs
          target: /home/yomiko/cronjobs
        - action: sync+restart
          path: ../entrypoint.sh
          target: /home/yomiko/entrypoint.sh
        - action: sync+restart
          path: ../lib
          target: /home/yomiko/lib
        - action: sync+restart
          path: ../migrations
          target: /home/yomiko/migrations
        - action: sync+restart
          path: ../server
          target: /home/yomiko/server
        - action: sync+restart
          path: ../web
          target: /home/yomiko/web
        - action: rebuild
          path: ./Dockerfile
    command: /home/yomiko/entrypoint.sh

# start with watch
#   mkdir -p data && docker compose -f docker/docker-compose.debug.yaml --project-name yomiko-debug watch

# exec
#   docker compose -f docker/docker-compose.debug.yaml --project-name yomiko-debug exec yomiko.debug bash

# call from host
#   curl 'http://localhost:62080/api/echo_inspector.sh?foo=bar'
#   curl 'http://localhost:62080/health'
