# https://git.busybox.net/busybox/tree/networking/httpd.c

# P:/url:[http://]hostname[:port]/new/path
P:/health:localhost/api/health.sh
P:/yomiko.user.js:localhost/api/install_userscript.sh

# .php:/path/php   # run xxx.php through an interpreter
*.sh:/bin/bash

# .au:audio/basic   # additional mime type for audio.au files
.webp:image/webp
